version: "3"
services: 
  fastapi:
    container_name: fastapi
    build: .
    ports: 
      - "${APP_PORT}:8000"
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 8000" 
    restart: always
