openapi: 3.0.3
info:
  title: Your API Name
  description: RESTful API built with FastAPI
  version: 0.1.0
servers:
  - url: http://your-domain
    description: Production Server
  - url: http://staging-your-domain
    description: Staging Server
paths:
